site_name: actibuilder
site_description: Actibuilder - web-application using Django REST and Angular2
repo_url: https://github.com/Kulturraum/actibuilder
site_dir: site
copyright: Copyright &copy; 2015, <a href="https://github.com/Kulturraum">Kulturraum</a>.

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
